# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.0'
gem 'rubocop', '~> 1.21'
gem 'rubocop-rspec', '~> 2.29'
gem 'webmock', '~> 3.23'

gem 'pry'
gem 'pry-rails'
